"""create app schema

Revision ID: 419bf84c6126
Revises: 0001_create_debug_log
Create Date: 2026-05-08 07:27:38.330287
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '419bf84c6126'
down_revision: Union[str, None] = '0001_create_debug_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greenhouse_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_profiles',
    sa.Column('crop_name', sa.String(length=255), nullable=False),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_opt', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('humidity_min', sa.Float(), nullable=True),
    sa.Column('humidity_opt', sa.Float(), nullable=True),
    sa.Column('humidity_max', sa.Float(), nullable=True),
    sa.Column('soil_moisture_min', sa.Float(), nullable=True),
    sa.Column('soil_moisture_opt', sa.Float(), nullable=True),
    sa.Column('soil_moisture_max', sa.Float(), nullable=True),
    sa.Column('co2_min', sa.Float(), nullable=True),
    sa.Column('co2_opt', sa.Float(), nullable=True),
    sa.Column('co2_max', sa.Float(), nullable=True),
    sa.Column('light_min', sa.Float(), nullable=True),
    sa.Column('light_opt', sa.Float(), nullable=True),
    sa.Column('light_max', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('greenhouses',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['greenhouse_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_control_policies',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['greenhouse_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_documents',
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['greenhouse_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_nodes',
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_key')
    )
    op.create_table('greenhouse_zones',
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actuator_registry',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('edge_node_id', sa.Uuid(), nullable=True),
    sa.Column('actuator_key', sa.String(length=255), nullable=False),
    sa.Column('actuator_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edge_node_id'], ['edge_nodes.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'actuator_key', name='uq_actuator_zone_key')
    )
    op.create_table('ai_conversations',
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['greenhouse_groups.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_log',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=True),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['greenhouse_groups.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_setpoints',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_target', sa.Float(), nullable=True),
    sa.Column('humidity_target', sa.Float(), nullable=True),
    sa.Column('soil_moisture_target', sa.Float(), nullable=True),
    sa.Column('co2_target', sa.Float(), nullable=True),
    sa.Column('light_target', sa.Float(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id')
    )
    op.create_table('plant_batches',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('cultivar', sa.String(length=255), nullable=True),
    sa.Column('planted_at', sa.Date(), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_registry',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('edge_node_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_key', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edge_node_id'], ['edge_nodes.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'sensor_key', name='uq_sensor_zone_key')
    )
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_tool_calls',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_log',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('greenhouse_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('actuator_id', sa.Uuid(), nullable=True),
    sa.Column('actuator_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuator_registry.id'], ),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['greenhouse_groups.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['greenhouse_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_log')
    op.drop_table('ai_tool_calls')
    op.drop_table('ai_messages')
    op.drop_table('sensor_registry')
    op.drop_table('plant_batches')
    op.drop_table('control_setpoints')
    op.drop_table('alert_log')
    op.drop_table('ai_conversations')
    op.drop_table('actuator_registry')
    op.drop_table('rag_chunks')
    op.drop_table('greenhouse_zones')
    op.drop_table('edge_nodes')
    op.drop_table('rag_documents')
    op.drop_table('group_control_policies')
    op.drop_table('greenhouses')
    op.drop_table('plant_profiles')
    op.drop_table('greenhouse_groups')
    # ### end Alembic commands ###
