user app
topic readwrite greenhouse-groups/#

user simulator
topic read greenhouse-groups/+/greenhouses/+/zones/+/commands
topic write greenhouse-groups/+/greenhouses/+/zones/+/telemetry
topic write greenhouse-groups/+/greenhouses/+/zones/+/state

user wokwi
topic read greenhouse-groups/+/greenhouses/+/zones/+/commands
topic write greenhouse-groups/+/greenhouses/+/zones/+/telemetry
topic write greenhouse-groups/+/greenhouses/+/zones/+/state
