persistence true
persistence_location /mosquitto/data

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

listener 1883
protocol mqtt

allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl.conf

max_connections -1
max_queued_messages 1000
